---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.profile }}-{{ .Release.Name }}
  namespace: {{ .Values.profile }}
  labels:
    {{- include "app.labels" . | nindent 4 }} 
spec:
  selector:
    {{- include "app.labels" . | nindent 4 }} 
  ports:
  {{- toYaml .Values.service.ports | nindent 4 }}
  type: NodePort