apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:
  name: ingress-{{ .Values.profile }}-{{ .Release.Name }}
  # namespace: {{ .Values.profile }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }} 
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
  {{- toYaml .Values.ingress.tls | nindent 2 }} 
  rules:
  {{- range .Values.ingress.rules }}
  - host: {{ .host | quote }}
    http:
      paths:
        {{- range .paths }}
        - path: {{ .path | quote }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ $.Values.profile }}-{{ $.Release.Name }}
              port:
                number: {{ .servicePort }}
        {{- end }}
  {{- end }}